name: Bygg og publiser plugin

on:
  release:
    types:
      - published

permissions:
  contents: read

jobs:
  publish-plugin-test:
    runs-on: ubuntu-latest
    steps:
      - name: Sjekk ut koden
        uses: actions/checkout@v4

      - name: Sett opp java
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'

      - name: Sett opp gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Bygg og publiser plugin
        run: ./gradlew publishPlugins
        env:
          GRADLE_PUBLISH_KEY: ${{ secrets.GRADLE_PUBLISH_KEY }}
          GRADLE_PUBLISH_SECRET: ${{ secrets.GRADLE_PUBLISH_SECRET }}
